import { 
  Sparkles, 
  Mic, 
  Brain, 
  Target, 
  TrendingUp, 
  Users, 
  CheckCircle, 
  ArrowRight,
  Play,
  Star,
  Quote,
  Zap,
  Shield,
  Clock
} from "lucide-react";
import Marquee from "react-fast-marquee";

import { Container } from "@/components/container";
import { Button } from "@/components/ui/button";
import { MarqueImg } from "@/components/marquee-img";
import { Link } from "react-router-dom";
import { useAuth } from "@clerk/clerk-react";

const HomePage = () => {
  const { userId } = useAuth();

  const features = [
    {
      icon: <Brain className="w-8 h-8 text-blue-600" />,
      title: "AI-Powered Questions",
      description: "Get role-specific technical questions generated by advanced AI models tailored to your experience level.",
      color: "from-blue-50 to-blue-100"
    },
    {
      icon: <Mic className="w-8 h-8 text-green-600" />,
      title: "Voice-Based Practice",
      description: "Practice your answers naturally using voice recognition technology for realistic interview simulation.",
      color: "from-green-50 to-green-100"
    },
    {
      icon: <Target className="w-8 h-8 text-purple-600" />,
      title: "Instant Feedback",
      description: "Receive detailed AI analysis and ratings on your responses with actionable improvement suggestions.",
      color: "from-purple-50 to-purple-100"
    },
    {
      icon: <TrendingUp className="w-8 h-8 text-orange-600" />,
      title: "Progress Tracking",
      description: "Monitor your interview performance over time and identify areas for continuous improvement.",
      color: "from-orange-50 to-orange-100"
    }
  ];

  const testimonials = [
    {
      name: "Sarah Chen",
      role: "Senior Frontend Developer",
      company: "TechCorp",
      rating: 5,
      text: "This platform completely transformed my interview preparation. The AI feedback was incredibly accurate and helped me land my dream job.",
      avatar: "/assets/img/office.jpg"
    },
    {
      name: "Michael Rodriguez",
      role: "Full Stack Engineer",
      company: "StartupXYZ",
      rating: 5,
      text: "The voice-based practice sessions made me much more confident. I could practice anywhere, anytime, and the feedback was spot-on.",
      avatar: "/assets/img/office.jpg"
    },
    {
      name: "Emily Watson",
      role: "DevOps Engineer",
      company: "CloudTech",
      rating: 5,
      text: "Finally, a platform that understands what technical interviews are really like. The questions are challenging but fair.",
      avatar: "/assets/img/office.jpg"
    }
  ];

  const stats = [
    { number: "250K+", label: "Offers Received", icon: <CheckCircle className="w-6 h-6 text-green-500" /> },
    { number: "1.2M+", label: "Interviews Aced", icon: <Zap className="w-6 h-6 text-yellow-500" /> },
    { number: "98%", label: "Success Rate", icon: <Shield className="w-6 h-6 text-blue-500" /> },
    { number: "50K+", label: "Active Users", icon: <Users className="w-6 h-6 text-purple-500" /> }
  ];

  const benefits = [
    {
      icon: <Clock className="w-6 h-6 text-blue-600" />,
      title: "Save Time",
      description: "Practice efficiently with AI-generated questions instead of researching interview topics"
    },
    {
      icon: <Brain className="w-6 h-6 text-green-600" />,
      title: "Smart Learning",
      description: "Get personalized feedback that adapts to your skill level and learning pace"
    },
    {
      icon: <Shield className="w-6 h-6 text-purple-600" />,
      title: "Build Confidence",
      description: "Practice in a safe environment and build the confidence to ace real interviews"
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-blue-50">
      {/* Hero Section */}
      <section className="relative overflow-hidden pt-20 pb-16">
        <Container>
          <div className="text-center max-w-4xl mx-auto">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-100 text-blue-700 text-sm font-medium mb-6 animate-fade-in">
              <Sparkles className="w-4 h-4" />
              AI-Powered Interview Preparation
            </div>
            
            <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold text-gray-900 mb-6 leading-tight animate-fade-in">
              Master Your
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600"> Interviews</span>
              <br />
              with AI
            </h1>
            
            <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto leading-relaxed animate-fade-in">
              Practice with AI-generated questions, get instant feedback on your answers, 
              and boost your confidence to ace any technical interview.
            </p>

            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12 animate-fade-in">
              {userId ? (
                <Link to="/generate">
                  <Button size="lg" className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white px-8 py-4 text-lg shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1">
                    Start Interview
                    <ArrowRight className="ml-2 w-5 h-5" />
                  </Button>
                </Link>
              ) : (
                <Link to="/signup">
                  <Button size="lg" className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white px-8 py-4 text-lg shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1">
                    Get Started Free
                    <ArrowRight className="ml-2 w-5 h-5" />
                  </Button>
                </Link>
              )}
              
              <Button variant="outline" size="lg" className="px-8 py-4 text-lg border-2 hover:bg-gray-50 transition-all duration-300">
                <Play className="mr-2 w-5 h-5" />
                Watch Demo
              </Button>
            </div>

            {/* Stats */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 max-w-4xl mx-auto">
              {stats.map((stat, index) => (
                <div key={index} className="text-center group hover:-translate-y-2 transition-all duration-300">
                  <div className="flex items-center justify-center mb-3">
                    {stat.icon}
                  </div>
                  <div className="text-3xl md:text-4xl font-bold text-gray-900 mb-2 group-hover:text-blue-600 transition-colors duration-300">
                    {stat.number}
                  </div>
                  <div className="text-sm text-gray-600 font-medium">
                    {stat.label}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </Container>

        {/* Background Elements */}
        <div className="absolute top-20 left-10 w-72 h-72 bg-blue-200 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob"></div>
        <div className="absolute top-40 right-10 w-72 h-72 bg-purple-200 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-2000"></div>
        <div className="absolute -bottom-8 left-20 w-72 h-72 bg-pink-200 rounded-full mix-blend-multiply filter blur-xl opacity-20 animate-blob animation-delay-4000"></div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 bg-white">
        <Container>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {benefits.map((benefit, index) => (
              <div key={index} className="text-center p-6 rounded-xl bg-gradient-to-br from-gray-50 to-white border border-gray-100 hover:shadow-lg transition-all duration-300 hover:-translate-y-1">
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-100 mb-4">
                  {benefit.icon}
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  {benefit.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {benefit.description}
                </p>
              </div>
            ))}
          </div>
        </Container>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-gradient-to-br from-gray-50 to-blue-50">
        <Container>
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Why Choose AI Mock Interview?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our platform combines cutting-edge AI technology with proven interview techniques 
              to give you the competitive edge you need.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className={`text-center p-6 rounded-xl bg-gradient-to-br ${feature.color} border border-gray-100 hover:shadow-lg transition-all duration-300 hover:-translate-y-1`}>
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-white shadow-sm mb-4">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </Container>
      </section>

      {/* How It Works Section */}
      <section className="py-20 bg-white">
        <Container>
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Get from preparation to success in just three simple steps
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center group">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-600 text-white text-2xl font-bold mb-4 group-hover:scale-110 transition-transform duration-300">
                1
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Create Your Interview
              </h3>
              <p className="text-gray-600">
                Specify your role, experience level, and tech stack to generate personalized questions.
              </p>
            </div>

            <div className="text-center group">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-600 text-white text-2xl font-bold mb-4 group-hover:scale-110 transition-transform duration-300">
                2
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Practice & Record
              </h3>
              <p className="text-gray-600">
                Answer questions using voice recognition and get real-time feedback on your responses.
              </p>
            </div>

            <div className="text-center group">
              <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-blue-600 text-white text-2xl font-bold mb-4 group-hover:scale-110 transition-transform duration-300">
                3
              </div>
              <h3 className="text-xl font-semibold text-gray-900 mb-3">
                Get AI Feedback
              </h3>
              <p className="text-gray-600">
                Receive detailed analysis, ratings, and improvement suggestions to enhance your skills.
              </p>
            </div>
          </div>
        </Container>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-gradient-to-br from-blue-50 to-indigo-50">
        <Container>
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              What Our Users Say
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Join thousands of developers who have transformed their interview skills
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-white p-6 rounded-xl border border-gray-100 hover:shadow-lg transition-all duration-300 hover:-translate-y-1">
                <div className="flex items-center gap-1 mb-4">
                  {[...Array(testimonial.rating)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
                
                <Quote className="w-8 h-8 text-blue-200 mb-4" />
                
                <p className="text-gray-700 mb-6 leading-relaxed">
                  "{testimonial.text}"
                </p>
                
                <div className="flex items-center gap-3">
                  <img 
                    src={testimonial.avatar} 
                    alt={testimonial.name}
                    className="w-12 h-12 rounded-full object-cover"
                  />
                  <div>
                    <div className="font-semibold text-gray-900">{testimonial.name}</div>
                    <div className="text-sm text-gray-600">{testimonial.role} at {testimonial.company}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </Container>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-blue-600 to-purple-600 relative overflow-hidden">
        <div className="absolute inset-0 bg-black/10"></div>
        <Container className="relative z-10">
          <div className="text-center text-white">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Ready to Ace Your Next Interview?
            </h2>
            <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
              Join thousands of developers who are already using AI Mock Interview 
              to boost their confidence and land their dream jobs.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              {userId ? (
                <Link to="/generate">
                  <Button size="lg" variant="secondary" className="px-8 py-4 text-lg shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1">
                    Start Interview Now
                    <ArrowRight className="ml-2 w-5 h-5" />
                  </Button>
                </Link>
              ) : (
                <Link to="/signup">
                  <Button size="lg" variant="secondary" className="px-8 py-4 text-lg shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1">
                    Get Started Free
                    <ArrowRight className="ml-2 w-5 h-5" />
                  </Button>
                </Link>
              )}
              
              <Button variant="outline" size="lg" className="px-8 py-4 text-lg border-white text-white hover:bg-white hover:text-blue-600 transition-all duration-300">
                Learn More
              </Button>
            </div>
          </div>
        </Container>
      </section>

      {/* Trusted By Section */}
      <section className="py-16 bg-gray-50">
        <Container>
          <div className="text-center mb-8">
            <p className="text-gray-600 font-medium">Trusted by leading companies worldwide</p>
          </div>
          
          <Marquee pauseOnHover className="py-4">
            <MarqueImg img="/assets/img/logo/firebase.png" />
            <MarqueImg img="/assets/img/logo/meet.png" />
            <MarqueImg img="/assets/img/logo/zoom.png" />
            <MarqueImg img="/assets/img/logo/microsoft.png" />
            <MarqueImg img="/assets/img/logo/tailwindcss.png" />
            <MarqueImg img="/assets/img/logo/react.png" />
          </Marquee>
        </Container>
      </section>
    </div>
  );
};

export default HomePage;
